check if goal exists

diff --git a/bee b/bee
--- a/bee
+++ b/bee
@@ -11,7 +11,7 @@ then
     exit 1
 else
     # check data
-    if [[ ! $3 =~ -?[0-9]+(\.[0-9]+)? ]]
+    if [[ ! $3 =~ ^-?[0-9]+(\.[0-9]+)?$ ]]
     then
         echo "data must be a number"
         exit 3
@@ -39,9 +39,17 @@ else
         fi
     fi
 
-    echo $timestamp
+    # check goals
+    
+    goals=$(curl -s "${base}users/${user}.json?auth_token=$key" |sed '#
+        s/^.*"goals":\[\(.*\)\].*$/\1/' )
 
-#     echo "${base}users/${user}.json?auth_token=$key"
+    if [[ ! $goals =~ \"${1}\" ]]
+    then
+        echo "Goal '$1' not found"
+        exit 1
+    fi
+
+    
     exit 0
 fi
-#'s/^.*"goals":\[\(.*\)\].*$/\1/'
